---
title: "MTH210: Lab 1"
format: 
  pdf:
    documentclass: article
editor: visual
geometry: margin=1in
header-includes:
   - \usepackage{amsmath, amssymb, setspace}
   - \onehalfspacing
   - \usepackage{etoolbox} 
   - \makeatletter 
   - \preto{\@verbatim}{\topsep=3pt \partopsep=3pt } 
   - \makeatother
---

## PNGR and Inverse Transform Method

(New code that you write for this assignment can be saved in new `*.R` files and pushed back to the repository.)

1.  Read through the code in `PRNG.R` that attempts to implement the multiplicative congruential method to generate pseudo-random numbers. (Some values are missing in those.) Try various values of $m$, $a$, and the seed $x_0$, and assess the performance of the generator.\

2.  Change the code in `PRNG.R` to implement the mixed congruential method. Is there much visible difference between these methods?\

3.  Write a function to generate a Bern$(p)$ random draw using Inverse Transform method. Call this function `myBern`.\

4.  For $p = .25$, call the `myBern` function 1000 times and come up with a method to check whether `myBern` is coded correctly.\

5.  Using only `runif()` function, write your version of the `sample` function, called `mySample`. It should have all the features of the `sample` function.
